### ISSUE TITLE
Doesn't download sedumi

### ISSUE THREAD

**Issue by sheim** [brandonjdehart/sedumi-pod#1]
The makefile seems to create a sedumi folder and add an "addpath_sedumi", but not actually download or build sedumi.

I'm not so familiar with makefiles yet, but if you're not in a rush I'll try to fix this soon-ish, I have a feeling it's relatively trivial.

**Comment by brandonjdehart** [comment]
Sedumi is included in this package as a submodule, so in order to have it download you need to do a git clone with the '--recursive' option on the end. Or, alternatively, if you've already got a clone of the repo then you can do a 'git submodule update --init' call inside the root of the repo and it should download the library.

I switched from a download model to the submodule at one point, because the git repository for sedumi is a few versions ahead of the downloadable version on their website.

**Comment by sheim** [comment]
Thanks, works fine.
